import { StyleSheet } from "react-native";
import { getCardVariants } from "../../theme/uiTokens";

export function createStyles(colors: any) {
  const { listItem } = getCardVariants(colors);
  return StyleSheet.create({
    container: {
      flex: 1,
      backgroundColor: colors.background,
    },
    headerInfo: {
      paddingHorizontal: 20,
      paddingTop: 8,
      paddingBottom: 8,
    },
    subtitle: {
      fontSize: 14,
      color: colors.muted,
    },
    submitBlocker: {
      ...StyleSheet.absoluteFillObject,
      backgroundColor: "#00000000",
      zIndex: 10,
    },
    keyboardAvoid: {
      flex: 1,
    },
    content: {
      paddingHorizontal: 20,
      paddingTop: 4,
    },
    scrollContent: {
      // increase bottom padding so bottom action buttons don't overlap content
      paddingBottom: 100,
    },
    section: {
      ...listItem,
      marginBottom: 16,
      padding: 16,
    },
    sectionCard: {
      ...listItem,
      padding: 16,
      marginBottom: 16,
    },
    sectionTitle: {
      fontSize: 17,
      fontWeight: "700",
      color: colors.text,
      marginBottom: 14,
    },
    stepper: {
      flexDirection: "row",
      gap: 8,
      marginBottom: 16,
    },
    stepButton: {
      flex: 1,
      paddingVertical: 10,
      paddingHorizontal: 6,
      borderRadius: 12,
      backgroundColor: colors.surface,
      flexDirection: "row",
      alignItems: "center",
      gap: 6,
    },
    stepButtonActive: {
      backgroundColor: colors.primarySoft,
    },
    stepButtonDisabled: {
      opacity: 0.5,
    },
    stepIndex: {
      fontSize: 13,
      fontWeight: "700",
      color: colors.muted,
      marginLeft: 2,
    },
    stepIndexWrap: {
      width: 14,
      height: 14,
      borderRadius: 16,
      alignItems: "center",
      justifyContent: "center",
      backgroundColor: colors.surface,
    },
    stepIndexWrapActive: {
      backgroundColor: colors.primarySoft,
    },
    stepIndexActive: {
      color: colors.primary,
    },
    stepLabel: {
      fontSize: 13,
      fontWeight: "600",
      color: colors.text,
      textAlign: "left",
      flexShrink: 1,
    },
    stepLabelActive: {
      color: colors.primary,
    },
    stepActions: {
      flexDirection: "row",
      gap: 12,
      marginTop: 4,
      marginBottom: 8,
    },

    fixedActions: {
      position: "absolute",
      left: 20,
      right: 20,
      bottom: 20,
      zIndex: 30,
    },
    fixedActionsBackground: {
      borderRadius: 14,
      padding: 8,
      overflow: "hidden",
      // use transparent background by default; blur will provide the frost effect
      backgroundColor: "transparent",
      borderWidth: 1,
      borderColor: "rgba(255,255,255,0.12)",
    },
    stepPrimary: {
      flex: 1,
      borderRadius: 12,
      paddingVertical: 12,
      alignItems: "center",
      backgroundColor: colors.primary,
    },
    stepPrimaryDisabled: {
      backgroundColor: colors.surface,
      borderWidth: 1,
      borderColor: colors.surfaceBorder,
      opacity: 0.5,
    },
    stepPrimaryText: {
      color: colors.onPrimary,
      fontWeight: "700",
      fontSize: 15,
    },
    stepPrimaryTextDisabled: {
      color: colors.muted,
    },
    stepSecondary: {
      flex: 1,
      borderColor: colors.primary,
      borderRadius: 12,
      paddingVertical: 12,
      alignItems: "center",
      backgroundColor: colors.surface,
    },
    stepSecondaryText: {
      color: colors.primary,
      fontWeight: "700",
      fontSize: 15,
    },
    row: {
      flexDirection: "row",
      gap: 12,
    },
    field: {
      marginTop: 8,
      marginBottom: 8,
    },
    label: {
      color: colors.text,
      marginBottom: 8,
      fontWeight: "600",
      fontSize: 15,
    },
    input: {
      borderWidth: 1,
      borderRadius: 12,
      paddingHorizontal: 16,
      paddingVertical: 0,
      height: 52,
      textAlignVertical: "center",
      color: colors.text,
      backgroundColor: colors.background,
      borderColor: colors.surfaceBorder,
      fontSize: 15,
      fontWeight: "500",
    },
    amountHeader: {
      flexDirection: "row",
      justifyContent: "space-between",
      alignItems: "center",
    },
    amountInput: {
      fontSize: 18,
      fontWeight: "700",
    },
    amountReset: {
      color: colors.primary,
      fontWeight: "600",
      fontSize: 13,
    },
    amountHint: {
      marginTop: 6,
      color: colors.muted,
      fontSize: 13,
      fontWeight: "500",
    },
    select: {
      borderWidth: 1,
      borderRadius: 12,
      paddingHorizontal: 16,
      paddingVertical: 14,
      backgroundColor: colors.background,
      borderColor: colors.surfaceBorder,
    },
    selectText: {
      color: colors.text,
      fontWeight: "600",
      fontSize: 15,
    },
    placeholder: {
      color: colors.muted,
      fontWeight: "500",
    },
    modalList: {
      maxHeight: 260,
    },
    dropdown: {
      borderWidth: 0,
      borderRadius: 12,
      padding: 12,
      backgroundColor: colors.background,
      marginBottom: 12,
      borderColor: colors.primarySoft,
      width: "96%",
      alignSelf: "center",
    },
    option: {
      paddingVertical: 10,
      borderBottomWidth: StyleSheet.hairlineWidth,
      borderBottomColor: colors.surfaceBorder,
    },
    optionTitle: {
      color: colors.text,
      fontWeight: "700",
    },
    optionSubtitle: {
      color: colors.muted,
      marginTop: 2,
    },
    searchBar: {
      flexDirection: "row",
      alignItems: "center",
      backgroundColor: colors.background,
      borderRadius: 12,
      paddingHorizontal: 12,
      paddingVertical: 10,
      marginBottom: 10,
      gap: 8,
      borderWidth: 1,
      borderColor: colors.primarySoft,
    },
    searchInput: {
      flex: 1,
      fontSize: 14,
      color: colors.text,
    },
    checkbox: {
      width: 24,
      height: 24,
      borderRadius: 6,
      borderWidth: 1,
      borderColor: colors.surfaceBorder,
      alignItems: "center",
      justifyContent: "center",
      backgroundColor: "transparent",
    },
    petCard: {
      ...listItem,
      padding: 14,
      marginBottom: 16,
    },
    petHeader: {
      flexDirection: "row",
      justifyContent: "space-between",
      alignItems: "center",
      marginBottom: 12,
    },
    petHeaderLeft: {
      flexDirection: "row",
      alignItems: "center",
      gap: 12,
    },
    petAvatar: {
      width: 44,
      height: 44,
      borderRadius: 22,
      backgroundColor: colors.background,
    },
    petAvatarPlaceholder: {
      width: 44,
      height: 44,
      borderRadius: 22,
      backgroundColor: colors.primarySoft,
      alignItems: "center",
      justifyContent: "center",
    },
    petAvatarText: {
      color: colors.primary,
      fontWeight: "700",
      fontSize: 16,
    },
    petTitle: {
      fontSize: 16,
      fontWeight: "700",
      color: colors.text,
    },
    petMeta: {
      color: colors.muted,
      fontSize: 12,
      marginTop: 4,
    },
    petSummary: {
      color: colors.muted,
      fontSize: 13,
      fontWeight: "600",
      marginBottom: 10,
    },
    addServiceButton: {
      alignSelf: "flex-start",
      paddingHorizontal: 12,
      paddingVertical: 8,
      borderRadius: 10,
    },
    addServiceText: {
      color: colors.primary,
      fontWeight: "700",
      fontSize: 13,
    },
    addPetButton: {
      alignItems: "center",
      paddingVertical: 12,
      borderRadius: 12,
    },
    addPetText: {
      color: colors.primary,
      fontWeight: "700",
      fontSize: 14,
    },
    removePetButton: {
      paddingHorizontal: 10,
      paddingVertical: 6,
      borderRadius: 8,
      backgroundColor: colors.primarySoft,
    },
    removePetText: {
      color: colors.primary,
      fontWeight: "600",
      fontSize: 12,
    },
    summaryRow: {
      flexDirection: "row",
      justifyContent: "space-between",
      alignItems: "center",
      paddingVertical: 8,
    },
    summaryCard: {
      borderWidth: 1,
      borderColor: colors.surfaceBorder,
      backgroundColor: colors.surface,
      borderRadius: 14,
      padding: 12,
      marginBottom: 12,
    },
    summaryTitle: {
      fontSize: 14,
      fontWeight: "700",
      color: colors.text,
      marginBottom: 8,
    },
    summaryLine: {
      marginBottom: 8,
    },
    summaryPet: {
      fontSize: 13,
      fontWeight: "700",
      color: colors.text,
    },
    summaryPetRow: {
      flexDirection: "row",
      alignItems: "center",
      gap: 10,
    },
    summaryServices: {
      fontSize: 13,
      color: colors.muted,
      marginTop: 2,
    },
    summaryServiceRow: {
      marginTop: 6,
    },
    summaryServiceName: {
      fontSize: 13,
      fontWeight: "600",
      color: colors.text,
    },
    summaryServiceMeta: {
      fontSize: 12,
      color: colors.muted,
      marginTop: 2,
    },
    summaryEmpty: {
      fontSize: 13,
      color: colors.muted,
    },
    summaryLabel: {
      color: colors.muted,
      fontWeight: "600",
    },
    summaryValue: {
      color: colors.text,
      fontWeight: "700",
      fontSize: 14,
    },
    segment: {
      flexDirection: "row",
      gap: 8,
      marginBottom: 20,
    },
    segmentButton: {
      flex: 1,
      paddingVertical: 12,
      borderWidth: 1.5,
      borderColor: colors.surfaceBorder,
      borderRadius: 12,
      alignItems: "center",
      backgroundColor: colors.surface,
    },
    segmentText: {
      fontWeight: "700",
      fontSize: 15,
      color: colors.text,
    },
    button: {
      borderRadius: 16,
      paddingVertical: 16,
      alignItems: "center",
      marginTop: 8,
      backgroundColor: colors.primary,
    },
    buttonText: {
      color: colors.onPrimary,
      fontWeight: "700",
      fontSize: 17,
    },
    secondary: {
      borderWidth: 1.5,
      borderRadius: 16,
      paddingVertical: 16,
      alignItems: "center",
      marginTop: 12,
      backgroundColor: colors.surface,
      borderColor: colors.primary,
    },
    secondaryText: {
      color: colors.primary,
      fontWeight: "700",
      fontSize: 17,
    },
    toggleRow: {
      flexDirection: "row",
      justifyContent: "space-between",
      alignItems: "center",
      borderRadius: 12,
      paddingHorizontal: 16,
    },
    reminderToggleLabel: {
      color: colors.text,
      fontWeight: "600",
      fontSize: 13,
    },
    reminderDefaultInline: {
      color: colors.muted,
      fontSize: 12,
      marginTop: 4,
    },
    reminderChipsRow: {
      flexDirection: "row",
      flexWrap: "wrap",
      gap: 8,
      marginBottom: 10,
    },
    reminderChip: {
      borderWidth: 1,
      borderColor: colors.surfaceBorder,
      borderRadius: 16,
      paddingHorizontal: 12,
      paddingVertical: 6,
      backgroundColor: colors.background,
    },
    reminderChipActive: {
      backgroundColor: colors.primarySoft,
      borderColor: colors.primary,
    },
    reminderChipText: {
      color: colors.text,
      fontSize: 12,
      fontWeight: "600",
    },
    reminderChipTextActive: {
      color: colors.primary,
    },
    reminderCustomRow: {
      flexDirection: "row",
      alignItems: "center",
      gap: 8,
    },
    reminderInput: {
      flex: 1,
      borderWidth: 1,
      borderColor: colors.surfaceBorder,
      borderRadius: 10,
      paddingHorizontal: 12,
      paddingVertical: 8,
      color: colors.text,
      backgroundColor: colors.background,
    },
    reminderAddButton: {
      paddingVertical: 8,
      paddingHorizontal: 14,
      borderRadius: 10,
      backgroundColor: colors.primary,
    },
    reminderAddButtonText: {
      color: colors.onPrimary,
      fontWeight: "700",
      fontSize: 12,
    },
    helperText: {
      color: colors.muted,
      fontSize: 13,
      marginTop: 4,
    },
    serviceMeta: {
      color: colors.muted,
      fontSize: 13,
      marginTop: 6,
      fontWeight: "600",
    },
    pricingCard: {
      backgroundColor: colors.surface,
      borderRadius: 14,
      borderWidth: 1,
      borderColor: colors.surfaceBorder,
      padding: 14,
      marginTop: 12,
      marginBottom: 8,
    },
    pricingTitle: {
      fontSize: 15,
      fontWeight: "700",
      color: colors.text,
      marginBottom: 10,
    },
    optionGroup: {
      gap: 8,
      marginBottom: 12,
    },
    optionCard: {
      borderRadius: 12,
      borderWidth: 1,
      borderColor: colors.surfaceBorder,
      backgroundColor: colors.background,
      padding: 12,
    },
    optionCardActive: {
      borderColor: colors.primary,
      backgroundColor: colors.primarySoft,
    },
    optionRow: {
      flexDirection: "row",
      justifyContent: "space-between",
      alignItems: "center",
      gap: 8,
    },
    optionPrice: {
      fontWeight: "700",
      color: colors.text,
    },
  });
}
