import { StyleSheet } from "react-native";
import { getCardStyle, getSegmentStyles } from "../theme/uiTokens";

export default function createStyles(colors: any) {
  const cardBase = getCardStyle(colors);
  const segment = getSegmentStyles(colors);
  return StyleSheet.create({
    container: {
      flex: 1,
      backgroundColor: colors.background,
    },
    scrollContent: {
      flexGrow: 1,
      padding: 24,
      paddingTop: 12
    },
    headerCard: {
      ...cardBase,
      padding: 18,
      marginBottom: 5,
    },
    headerRow: {
      flexDirection: "row",
      alignItems: "center",
    },
    avatar: {
      height: 64,
      width: 64,
      borderRadius: 12,
      backgroundColor: colors.surface,
      borderWidth: 0,
      borderColor: colors.surface,
      alignItems: "center",
      justifyContent: "center",
      marginRight: 14,
      shadowColor: "#000",
      shadowOpacity: 0.05,
      shadowRadius: 10,
      shadowOffset: { width: 0, height: 4 },
      elevation: 4,
    },
    headerInfo: {
      flex: 1,
    },
    headerTopRow: {
      flexDirection: "row",
      alignItems: "center",
      justifyContent: "space-between",
      marginBottom: 4,
    },
    avatarText: {
      color: colors.primary,
      fontWeight: "800",
      fontSize: 24,
    },
    headerLabel: {
      color: colors.muted,
      fontSize: 12,
      letterSpacing: 1.2,
      textTransform: "uppercase",
    },
    headerTitle: {
      color: colors.text,
      fontSize: 22,
      fontWeight: "700",
    },
    accountSwitcher: {
      flexDirection: "row",
      alignItems: "center",
      alignSelf: "flex-start",
      marginTop: 8,
      paddingHorizontal: 10,
      paddingVertical: 6,
      borderRadius: 10,
      backgroundColor: colors.surface,
      borderWidth: 1,
      borderColor: colors.surfaceBorder,
      shadowColor: "#000",
      shadowOpacity: 0.03,
      shadowRadius: 6,
      shadowOffset: { width: 0, height: 2 },
      elevation: 2,
    },
    accountSwitcherText: {
      color: colors.muted,
      marginRight: 6,
      maxWidth: 160,
      fontSize: 13,
      fontWeight: "600",
    },
    headerSubtitle: {
      color: colors.muted,
      marginTop: 2,
    },
    headerDetail: {
      color: colors.muted,
      marginTop: 2,
      fontSize: 13,
    },
    headerMeta: {
      color: colors.muted,
      fontSize: 12,
      marginTop: 6,
    },
    avatarImage: {
      width: "100%",
      height: "100%",
      borderRadius: 10,
    },
    avatarBadge: {
      position: "absolute",
      bottom: -4,
      right: -4,
      backgroundColor: colors.primary,
      width: 24,
      height: 24,
      borderRadius: 12,
      alignItems: "center",
      justifyContent: "center",
      borderWidth: 2,
      borderColor: colors.surface,
    },
    avatarBadgeText: {
      fontSize: 12,
    },
    avatarLoading: {
      position: "absolute",
      top: 0,
      left: 0,
      right: 0,
      bottom: 0,
      backgroundColor: "rgba(0, 0, 0, 0.5)",
      borderRadius: 10,
      alignItems: "center",
      justifyContent: "center",
    },
    inputField: {
      backgroundColor: colors.background,
      borderWidth: 1,
      borderColor: colors.surfaceBorder,
      borderRadius: 12,
      paddingHorizontal: 16,
      paddingVertical: 12,
      color: colors.text,
      fontSize: 15,
      fontWeight: "400",
      marginTop: 4,
    },
    passwordInputRow: {
      backgroundColor: colors.background,
      borderWidth: 1,
      borderColor: colors.surfaceBorder,
      borderRadius: 12,
      paddingHorizontal: 12,
      paddingVertical: 6,
      marginTop: 4,
      flexDirection: "row",
      alignItems: "center",
    },
    passwordInput: {
      flex: 1,
      color: colors.text,
      fontSize: 15,
      fontWeight: "400",
      paddingVertical: 6,
      paddingHorizontal: 4,
    },
    error: {
      color: colors.danger,
      marginBottom: 8,
    },
    section: {
      ...cardBase,
      marginTop: 12,
      padding: 18,
    },
    sectionTabs: {
      ...segment.container,
      marginTop: 12,
      width: "100%",
      paddingHorizontal: 12,
    },
    sectionTab: {
      ...segment.button,
      paddingVertical: 10,
    },
    sectionTabActive: {
      ...segment.buttonActive,
    },
    sectionTabText: {
      ...segment.text,
    },
    sectionTabTextActive: {
      ...segment.textActive,
    },
    inputRow: {
      flexDirection: "row",
      gap: 12,
    },
    subsectionTitle: {
      color: colors.text,
      fontWeight: "700",
      marginTop: 8,
      marginBottom: 12,
    },
    inputGroup: {
      flex: 1,
      marginBottom: 10,
    },
    inputLabel: {
      color: colors.muted,
      fontSize: 11,
      letterSpacing: 0.6,
      textTransform: "uppercase",
      marginBottom: 6,
    },
    inputLabelRegular: {
      fontWeight: "400",
    },
    phoneField: {
      marginBottom: 0,
    },
    languageOptions: {
      flexDirection: "row",
      gap: 12,
      marginTop: 8,
    },
    languageOption: {
      flex: 1,
      backgroundColor: colors.surface,
      borderRadius: 12,
      paddingVertical: 12,
      alignItems: "center",
      shadowColor: "#000",
      shadowOpacity: 0.05,
      shadowRadius: 10,
      shadowOffset: { width: 0, height: 4 },
      elevation: 3,
    },
    languageOptionActive: {
      backgroundColor: colors.primarySoft,
    },
    languageOptionText: {
      color: colors.muted,
      fontWeight: "600",
      fontSize: 14,
    },
    languageOptionTextActive: {
      color: colors.primary,
      fontWeight: "700",
    },
    modeOptions: {
      flexDirection: "row",
      gap: 12,
      marginTop: 8,
    },
    modeOption: {
      flex: 1,
      backgroundColor: colors.surface,
      borderRadius: 8,
      paddingVertical: 8,
      alignItems: "center",
    },
    modeOptionActive: {},
    modeOptionText: {
      color: colors.muted,
      fontWeight: "600",
      fontSize: 14,
    },
    modeOptionTextActive: {
      color: colors.primary,
      fontWeight: "700",
    },
    sectionTitle: {
      color: colors.text,
      fontWeight: "700",
      fontSize: 16,
      marginBottom: 8,
    },
    sectionText: {
      color: colors.muted,
      marginBottom: 12,
    },
    colorGrid: {
      flexDirection: "row",
      flexWrap: "wrap",
      gap: 12,
    },
    colorCell: {
      width: "48%",
    },
    colorLabel: {
      color: colors.muted,
      fontSize: 12,
      marginBottom: 4,
    },
    colorInputRow: {
      flexDirection: "row",
      alignItems: "center",
      gap: 8,
    },
    colorSwatchTouchable: {
      borderRadius: 12,
      borderWidth: 1,
      borderColor: colors.surfaceBorder,
      overflow: "hidden",
      shadowColor: "#000",
      shadowOpacity: 0.08,
      shadowRadius: 6,
      shadowOffset: { width: 0, height: 2 },
      elevation: 3,
    },
    colorSwatch: {
      width: 40,
      height: 40,
      borderRadius: 12,
      borderWidth: 1,
      borderColor: "rgba(255,255,255,0.4)",
    },
    colorInput: {
      flex: 1,
      height: 40,
      borderRadius: 10,
      borderWidth: 1,
      borderColor: colors.surfaceBorder,
      backgroundColor: colors.surface,
      paddingHorizontal: 10,
      color: colors.text,
      fontSize: 14,
    },
    colorPickerBackdrop: {
      flex: 1,
      backgroundColor: "rgba(0,0,0,0.45)",
      justifyContent: "center",
      alignItems: "center",
      padding: 20,
    },
    colorPickerCard: {
      width: "100%",
      maxWidth: 400,
      borderRadius: 12,
      backgroundColor: colors.surface,
      padding: 16,
    },
    colorPickerTitle: {
      color: colors.text,
      fontWeight: "600",
      marginBottom: 12,
    },
    colorPickerComponent: {
      width: "100%",
      height: 240,
    },
    roleBadge: {
      alignSelf: "flex-start",
      paddingHorizontal: 8,
      paddingVertical: 4,
      borderRadius: 12,
      backgroundColor: colors.primarySoft,
      borderWidth: 1,
      borderColor: colors.primary,
    },
    roleBadgeText: {
      color: colors.primary,
      fontWeight: "600",
      fontSize: 12,
    },
    marketplaceMediaGrid: {
      flexDirection: "row",
      flexWrap: "wrap",
      gap: 12,
      marginBottom: 12,
    },
    marketplaceMediaCard: {
      ...cardBase,
      flex: 1,
      minWidth: 150,
      padding: 12,
    },
    marketplaceMediaTitle: {
      fontSize: 13,
      fontWeight: "700",
      color: colors.text,
      marginBottom: 8,
    },
    marketplaceLogo: {
      height: 96,
      borderRadius: 12,
      backgroundColor: colors.background,
      alignItems: "center",
      justifyContent: "center",
      overflow: "hidden",
      position: "relative",
    },
    marketplaceLogoImage: {
      width: "100%",
      height: "100%",
    },
    marketplaceLogoFallback: {
      fontSize: 24,
      fontWeight: "800",
      color: colors.primary,
    },
    marketplaceHero: {
      height: 96,
      borderRadius: 12,
      backgroundColor: colors.background,
      alignItems: "center",
      justifyContent: "center",
      overflow: "hidden",
      position: "relative",
    },
    marketplaceHeroImage: {
      width: "100%",
      height: "100%",
    },
    marketplaceHeroPlaceholder: {
      paddingHorizontal: 8,
    },
    marketplaceHeroPlaceholderText: {
      color: colors.muted,
      fontSize: 12,
      textAlign: "center",
    },
    marketplaceMediaOverlay: {
      position: "absolute",
      top: 0,
      right: 0,
      bottom: 0,
      left: 0,
      backgroundColor: "rgba(0,0,0,0.35)",
      alignItems: "center",
      justifyContent: "center",
    },
    marketplaceMediaButton: {
      marginTop: 10,
      borderRadius: 10,
      paddingVertical: 10,
      alignItems: "center",
      backgroundColor: colors.primarySoft,
      shadowColor: "#000",
      shadowOpacity: 0.04,
      shadowRadius: 8,
      shadowOffset: { width: 0, height: 3 },
      elevation: 2,
    },
    marketplaceMediaButtonText: {
      color: colors.primary,
      fontWeight: "700",
      fontSize: 12,
    },
    toggleRow: {
      flexDirection: "row",
      alignItems: "center",
      justifyContent: "space-between",
      paddingVertical: 6,
    },
    toggleTextGroup: {
      flex: 1,
      paddingRight: 12,
    },
    toggleLabel: {
      color: colors.text,
      fontSize: 14,
      fontWeight: "600",
    },
    toggleHelper: {
      color: colors.muted,
      fontSize: 12,
      marginTop: 2,
    },
    toggleGroup: {
      marginTop: 12,
      paddingTop: 12,
      borderTopWidth: 1,
      borderTopColor: colors.surfaceBorder,
    },
    toggleGroupLabel: {
      color: colors.muted,
      fontSize: 11,
      letterSpacing: 0.6,
      textTransform: "uppercase",
      marginBottom: 6,
    },
    reminderGroup: {
      marginTop: 8,
      paddingTop: 8,
      borderTopWidth: 1,
      borderTopColor: colors.surfaceBorder,
    },
    reminderTitle: {
      color: colors.text,
      fontSize: 13,
      fontWeight: "600",
    },
    reminderHelper: {
      color: colors.muted,
      fontSize: 12,
      marginTop: 2,
      marginBottom: 8,
    },
    reminderChipsRow: {
      flexDirection: "row",
      flexWrap: "wrap",
      gap: 8,
      marginBottom: 10,
    },
    reminderChip: {
      borderWidth: 0,
      borderColor: "transparent",
      borderRadius: 16,
      paddingHorizontal: 12,
      paddingVertical: 6,
      backgroundColor: colors.surface,
      shadowColor: "#000",
      shadowOpacity: 0.04,
      shadowRadius: 8,
      shadowOffset: { width: 0, height: 3 },
      elevation: 2,
    },
    reminderChipActive: {
      backgroundColor: colors.primarySoft,
    },
    reminderChipDisabled: {
      opacity: 0.5,
    },
    reminderChipText: {
      color: colors.text,
      fontSize: 12,
      fontWeight: "600",
    },
    reminderChipTextActive: {
      color: colors.primary,
    },
    reminderChipTextDisabled: {
      color: colors.muted,
    },
    reminderCustomRow: {
      flexDirection: "row",
      alignItems: "center",
      gap: 8,
    },
    reminderInput: {
      flex: 1,
      borderWidth: 0,
      borderColor: "transparent",
      borderRadius: 10,
      paddingHorizontal: 12,
      paddingVertical: 8,
      color: colors.text,
      backgroundColor: colors.surface,
      shadowColor: "#000",
      shadowOpacity: 0.04,
      shadowRadius: 8,
      shadowOffset: { width: 0, height: 3 },
      elevation: 2,
    },
    reminderInputDisabled: {
      backgroundColor: colors.surface,
      color: colors.muted,
    },
    reminderAddButton: {
      paddingVertical: 8,
      paddingHorizontal: 14,
      borderRadius: 10,
      backgroundColor: colors.primary,
    },
    reminderAddButtonDisabled: {
      backgroundColor: colors.surfaceBorder,
    },
    reminderAddButtonText: {
      color: colors.onPrimary,
      fontWeight: "700",
      fontSize: 12,
    },
    linkGroup: {
      gap: 12,
    },
    linkButton: {
      backgroundColor: colors.surface,
      borderWidth: 0,
      borderColor: colors.surface,
      borderRadius: 12,
      paddingVertical: 12,
      alignItems: "center",
      shadowColor: "#000",
      shadowOpacity: 0.05,
      shadowRadius: 10,
      shadowOffset: { width: 0, height: 4 },
      elevation: 3,
    },
    linkButtonContent: {
      flexDirection: "row",
      alignItems: "center",
      justifyContent: "center",
      gap: 10,
    },
    linkButtonText: {
      color: colors.text,
      fontWeight: "700",
      fontSize: 15,
    },
    buttonDisabled: {
      opacity: 0.6,
    },
    actionRow: {
      flexDirection: "row",
      gap: 12,
      marginTop: 8,
    },
    button: {
      backgroundColor: colors.primary,
      borderRadius: 10,
      paddingVertical: 12,
      paddingHorizontal: 18,
      minWidth: 110,
      justifyContent: "center",
      alignItems: "center",
      marginBottom: 0,
    },
    buttonInline: {
      flex: 1,
      marginBottom: 0,
    },
    buttonText: {
      color: colors.onPrimary,
      fontWeight: "700",
      fontSize: 16,
    },
    secondary: {
      backgroundColor: colors.surface,
      borderWidth: 1,
      borderColor: colors.surfaceBorder,
    },
    buttonTextSecondary: {
      color: colors.text,
      fontWeight: "700",
      fontSize: 16,
    },
    danger: {
      backgroundColor: "#ef4444",
    },
    footerVersion: {
      marginTop: 6,
      color: colors.muted,
      fontSize: 11,
      textAlign: "center",
    },
  });
}
